
spring.application.name=arsen-app
server.port = 8081
spring.datasource.url=jdbc:mysql://localhost:3306/store?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=amiars05052006A!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
